### ISSUE TITLE
TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by JameShao1314** [tyliupku/wiki2bio#3]
When training, I encountered the following problem:
`field-gated encoder LSTM
Traceback (most recent call last):
  File "Main.py", line 230, in <module>
    main()
  File "Main.py", line 217, in main
    encoder_add_pos=FLAGS.encoder_pos, learning_rate=FLAGS.learning_rate)
  File "/export/shaotong/wiki2bio-master/SeqUnit.py", line 71, in __init__
    self.dec_lstm = LstmUnit(self.hidden_size, self.emb_size, 'decoder_lstm')
  File "/export/shaotong/wiki2bio-master/LstmUnit.py", line 19, in __init__
    self.b = tf.get_variable('b', [4*self.hidden_size], initializer=tf.zeros_initializer([4*self.hidden_size]), dtype=tf.float32)
  File "/export/shaotong/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/init_ops.py", line 94, in __init__
    self.dtype = dtypes.as_dtype(dtype)
  File "/export/shaotong/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/dtypes.py", line 673, in as_dtype
    return _INTERN_TABLE[type_value]
TypeError: unhashable type: 'list'
`
Is this related to the version of Python/Tensorflow or anything in the requirement.txt (which is missing)? I'm confused because I didn't see the "list" type in the related code. Anyone has suggestions?

**Comment by erwin-d-austria** [comment]
Do you figure out where is the requirement.txt?

**Comment by JameShao1314** [comment]
Update: This has been fixed. 
Change line 19 to:
 self.b = tf.get_variable('b', [4*self.hidden_size], initializer=tf.zeros_initializer(), dtype=tf.float32)

**Comment by JameShao1314** [comment]
@erwin-d-austria I installed Tensorflow 1.2, and also installed NTLK.

**Comment by erwin-d-austria** [comment]
@JameShao1314 have you run the code without error?
